# Generated by Django 2.2.2 on 2019-08-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_debate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
